# Generated by Django 5.0.2 on 2024-02-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
